services:
  frmcompanion:
    image: ghcr.io/prestonr83/ficsit-remote-monitoring-companion:latest
    restart: unless-stopped
    environment:
      - FRM_HOST=${FRM_HOST:-satisfactory-server}
      - FRM_PORT=${FRM_PORT:-8080}
      - FRM_HOSTS=${FRM_HOSTS:-}
    ports:
      - "9000:9000"

  prometheus:
    image: ghcr.io/prestonr83/satisfactory-monitoring-prometheus:latest
    restart: unless-stopped
    environment:
      - POWER_CONSUMED_OVERHEAD_MULTIPLIER=${POWER_CONSUMED_OVERHEAD_MULTIPLIER:-1.2}
      - POWER_CONSUMED_OVERHEAD_WINDOW=${POWER_CONSUMED_OVERHEAD_WINDOW:-6h}
      - POWER_MAX_CONSUMED_WINDOW=${POWER_MAX_CONSUMED_WINDOW:-1h}
      - FUSE_TRIGGERED_THRESHOLD=${FUSE_TRIGGERED_THRESHOLD:-0}
      - FUSE_TRIGGERED_FOR=${FUSE_TRIGGERED_FOR:-0s}
      - BATTERY_DRAINED_MINUTES=${BATTERY_DRAINED_MINUTES:-900}
      - BATTERY_DRAINED_FOR=${BATTERY_DRAINED_FOR:-10s}
      - BATTERY_DRAINING_THRESHOLD=${BATTERY_DRAINING_THRESHOLD:-0}
      - BATTERY_DRAINING_FOR=${BATTERY_DRAINING_FOR:-10s}
      - MAX_CONSUMPTION_CAPACITY_MULTIPLIER=${MAX_CONSUMPTION_CAPACITY_MULTIPLIER:-1}
      - MAX_CONSUMPTION_FOR=${MAX_CONSUMPTION_FOR:-10s}
      - OVERCONSUMING_DIFFERENCE_THRESHOLD=${OVERCONSUMING_DIFFERENCE_THRESHOLD:-0}
      - OVERCONSUMING_FOR=${OVERCONSUMING_FOR:-1m}
      - UNDERPRODUCING_CAPACITY_PC=${UNDERPRODUCING_CAPACITY_PC:-0.2}
      - UNDERPRODUCING_CAPACITY_PERCENT=${UNDERPRODUCING_CAPACITY_PERCENT:-20}
      - UNDERPRODUCING_FOR=${UNDERPRODUCING_FOR:-1m}
      - TRAIN_DERAILED_THRESHOLD=${TRAIN_DERAILED_THRESHOLD:-0}
      - TRAIN_DERAILED_FOR=${TRAIN_DERAILED_FOR:-0s}
    volumes:
      - prometheus-config:/etc/prometheus
      - prometheus:/prometheus
    ports:
      - "9090:9090"

  frmcache:
    image: ghcr.io/prestonr83/ficsit-remote-monitoring-cache:latest
    restart: unless-stopped
    environment:
      - FRM_HOST=${FRM_HOST:-satisfactory-server}
      - FRM_PORT=${FRM_PORT:-8080}
      - FRM_HOSTS=${FRM_HOSTS:-}
      - PG_HOST=${PG_HOST:-postgres}
      - PG_PORT=${PG_PORT:-5432}
      - PG_PASSWORD=${PG_PASSWORD:-secretpassword}
      - PG_USER=${PG_USER:-postgres}
      - PG_DB=${PG_DB:-postgres}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD:-secretpassword}
    volumes:
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  alertmanager-config:
    image: ghcr.io/prestonr83/ficsit-remote-monitoring-alertmanager-config:latest
    volumes:
      - alertmanager-config:/etc/alertmanager
    environment:
      - FRM_HOST=${FRM_HOST:-satisfactory-server}
      - FRM_PORT=${FRM_PORT:-8080}
      - FRM_HOSTS=${FRM_HOSTS:-}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK:-}
      - DISCORD_WEBHOOKS=${DISCORD_WEBHOOKS:-}
      - OUTPUT_PATH=/etc/alertmanager/alertmanager.yml

  alertmanager:
    image: ghcr.io/prestonr83/satisfactory-monitoring-alertmanager:latest
    restart: unless-stopped
    volumes:
      - alertmanager-config:/etc/alertmanager
      - alertmanager:/alertmanager
    ports:
      - "9093:9093"
    depends_on:
      alertmanager-config:
        condition: service_completed_successfully
        restart: true

  grafana:
    image: ghcr.io/prestonr83/satisfactory-monitoring-grafana:latest
    restart: unless-stopped
    volumes:
      - grafana-provisioning:/etc/grafana/provisioning
      - grafana-dashboards:/etc/grafana/dashboards
      - grafana-icons:/usr/share/grafana/public/img/icons/satisfactory
      - grafana-public-dashboards:/usr/share/grafana/public/dashboards
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  grafana:
  grafana-provisioning:
  grafana-dashboards:
  grafana-icons:
  grafana-public-dashboards:
  alertmanager:
  alertmanager-config:
  postgresql:
  prometheus:
  prometheus-config:

networks:
  default:
    external: true
    name: satisfactory_server_default
