services:
  frmcompanion:
    image: ghcr.io/prestonr83/ficsit-remote-monitoring-companion:latest
    restart: unless-stopped
    environment:
      - FRM_HOST=${FRM_HOST:-satisfactory-server}
      - FRM_PORT=${FRM_PORT:-8080}
      - FRM_HOSTS=${FRM_HOSTS:-}
    ports:
      - "9000:9000"

  prometheus:
    image: ghcr.io/prestonr83/satisfactory-monitoring-prometheus:latest
    restart: unless-stopped
    volumes:
      - prometheus:/prometheus
    ports:
      - "9090:9090"

  frmcache:
    image: ghcr.io/prestonr83/ficsit-remote-monitoring-cache:latest
    restart: unless-stopped
    environment:
      - FRM_HOST=${FRM_HOST:-satisfactory-server}
      - FRM_PORT=${FRM_PORT:-8080}
      - FRM_HOSTS=${FRM_HOSTS:-}
      - PG_HOST=${PG_HOST:-postgres}
      - PG_PORT=${PG_PORT:-5432}
      - PG_PASSWORD=${PG_PASSWORD:-secretpassword}
      - PG_USER=${PG_USER:-postgres}
      - PG_DB=${PG_DB:-postgres}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD:-secretpassword}
    volumes:
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  alertmanager-config:
    image: ghcr.io/prestonr83/ficsit-remote-monitoring-alertmanager-config:latest
    volumes:
      - alertmanager-config:/generated
    environment:
      - FRM_HOST=${FRM_HOST:-satisfactory-server}
      - FRM_PORT=${FRM_PORT:-8080}
      - FRM_HOSTS=${FRM_HOSTS:-}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK:-}
      - DISCORD_WEBHOOKS=${DISCORD_WEBHOOKS:-}
      - OUTPUT_PATH=/generated/alertmanager.yml

  alertmanager:
    image: ghcr.io/prestonr83/satisfactory-monitoring-alertmanager:latest
    restart: unless-stopped
    volumes:
      - alertmanager-config:/generated
      - alertmanager:/alertmanager
    command:
      - --config.file=/generated/alertmanager.yml
      - --storage.path=/alertmanager
    ports:
      - "9093:9093"
    depends_on:
      alertmanager-config:
        condition: service_completed_successfully
        restart: true

  grafana:
    image: ghcr.io/prestonr83/satisfactory-monitoring-grafana:latest
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  grafana:
  alertmanager:
  alertmanager-config:
  postgresql:
  prometheus:

networks:
  default:
    external: true
    name: satisfactory_server_default
