#!/bin/sh
set -eu

POWER_CONSUMED_OVERHEAD_MULTIPLIER="${POWER_CONSUMED_OVERHEAD_MULTIPLIER:-1.2}"
POWER_CONSUMED_OVERHEAD_WINDOW="${POWER_CONSUMED_OVERHEAD_WINDOW:-6h}"
POWER_MAX_CONSUMED_WINDOW="${POWER_MAX_CONSUMED_WINDOW:-1h}"
FUSE_TRIGGERED_THRESHOLD="${FUSE_TRIGGERED_THRESHOLD:-0}"
FUSE_TRIGGERED_FOR="${FUSE_TRIGGERED_FOR:-0s}"
BATTERY_DRAINED_MINUTES="${BATTERY_DRAINED_MINUTES:-1800}"
BATTERY_DRAINED_FOR="${BATTERY_DRAINED_FOR:-10s}"
BATTERY_DRAINING_THRESHOLD="${BATTERY_DRAINING_THRESHOLD:-0}"
BATTERY_DRAINING_FOR="${BATTERY_DRAINING_FOR:-10s}"
MAX_CONSUMPTION_CAPACITY_MULTIPLIER="${MAX_CONSUMPTION_CAPACITY_MULTIPLIER:-1}"
MAX_CONSUMPTION_FOR="${MAX_CONSUMPTION_FOR:-10s}"
OVERCONSUMING_DIFFERENCE_THRESHOLD="${OVERCONSUMING_DIFFERENCE_THRESHOLD:-0}"
OVERCONSUMING_FOR="${OVERCONSUMING_FOR:-1m}"
UNDERPRODUCING_CAPACITY_PC="${UNDERPRODUCING_CAPACITY_PC:-0.2}"
UNDERPRODUCING_CAPACITY_PERCENT="${UNDERPRODUCING_CAPACITY_PERCENT:-20}"
UNDERPRODUCING_FOR="${UNDERPRODUCING_FOR:-1m}"
TRAIN_DERAILED_THRESHOLD="${TRAIN_DERAILED_THRESHOLD:-0}"
TRAIN_DERAILED_FOR="${TRAIN_DERAILED_FOR:-0s}"

export POWER_CONSUMED_OVERHEAD_MULTIPLIER POWER_CONSUMED_OVERHEAD_WINDOW POWER_MAX_CONSUMED_WINDOW
export FUSE_TRIGGERED_THRESHOLD FUSE_TRIGGERED_FOR BATTERY_DRAINED_MINUTES BATTERY_DRAINED_FOR
export BATTERY_DRAINING_THRESHOLD BATTERY_DRAINING_FOR MAX_CONSUMPTION_CAPACITY_MULTIPLIER MAX_CONSUMPTION_FOR
export OVERCONSUMING_DIFFERENCE_THRESHOLD OVERCONSUMING_FOR UNDERPRODUCING_CAPACITY_PC UNDERPRODUCING_CAPACITY_PERCENT UNDERPRODUCING_FOR
export TRAIN_DERAILED_THRESHOLD TRAIN_DERAILED_FOR

mkdir -p /etc/prometheus

if [ ! -f /etc/prometheus/prometheus.yml ]; then
  cp /opt/satisfactory-monitoring/defaults/prometheus/prometheus.yml /etc/prometheus/prometheus.yml
fi

if [ ! -d /etc/prometheus/nodes ] || [ -z "$(find /etc/prometheus/nodes -type f 2>/dev/null)" ]; then
  mkdir -p /etc/prometheus/nodes
  cp -R /opt/satisfactory-monitoring/defaults/prometheus/nodes/. /etc/prometheus/nodes/
fi

if [ ! -d /etc/prometheus/rules ] || [ -z "$(find /etc/prometheus/rules -type f 2>/dev/null)" ]; then
  mkdir -p /etc/prometheus/rules
  cp -R /opt/satisfactory-monitoring/defaults/prometheus/rules/. /etc/prometheus/rules/
fi

find /etc/prometheus/rules -type f -name '*.yml' | while IFS= read -r file; do
  sed -i \
    -e "s|\${POWER_CONSUMED_OVERHEAD_MULTIPLIER}|${POWER_CONSUMED_OVERHEAD_MULTIPLIER}|g" \
    -e "s|\${POWER_CONSUMED_OVERHEAD_WINDOW}|${POWER_CONSUMED_OVERHEAD_WINDOW}|g" \
    -e "s|\${POWER_MAX_CONSUMED_WINDOW}|${POWER_MAX_CONSUMED_WINDOW}|g" \
    -e "s|\${FUSE_TRIGGERED_THRESHOLD}|${FUSE_TRIGGERED_THRESHOLD}|g" \
    -e "s|\${FUSE_TRIGGERED_FOR}|${FUSE_TRIGGERED_FOR}|g" \
    -e "s|\${BATTERY_DRAINED_MINUTES}|${BATTERY_DRAINED_MINUTES}|g" \
    -e "s|\${BATTERY_DRAINED_FOR}|${BATTERY_DRAINED_FOR}|g" \
    -e "s|\${BATTERY_DRAINING_THRESHOLD}|${BATTERY_DRAINING_THRESHOLD}|g" \
    -e "s|\${BATTERY_DRAINING_FOR}|${BATTERY_DRAINING_FOR}|g" \
    -e "s|\${MAX_CONSUMPTION_CAPACITY_MULTIPLIER}|${MAX_CONSUMPTION_CAPACITY_MULTIPLIER}|g" \
    -e "s|\${MAX_CONSUMPTION_FOR}|${MAX_CONSUMPTION_FOR}|g" \
    -e "s|\${OVERCONSUMING_DIFFERENCE_THRESHOLD}|${OVERCONSUMING_DIFFERENCE_THRESHOLD}|g" \
    -e "s|\${OVERCONSUMING_FOR}|${OVERCONSUMING_FOR}|g" \
    -e "s|\${UNDERPRODUCING_CAPACITY_PC}|${UNDERPRODUCING_CAPACITY_PC}|g" \
    -e "s|\${UNDERPRODUCING_CAPACITY_PERCENT}|${UNDERPRODUCING_CAPACITY_PERCENT}|g" \
    -e "s|\${UNDERPRODUCING_FOR}|${UNDERPRODUCING_FOR}|g" \
    -e "s|\${TRAIN_DERAILED_THRESHOLD}|${TRAIN_DERAILED_THRESHOLD}|g" \
    -e "s|\${TRAIN_DERAILED_FOR}|${TRAIN_DERAILED_FOR}|g" \
    "$file"
done

exec /bin/prometheus --config.file=/etc/prometheus/prometheus.yml "$@"
